tributech-agent:
    ...
    environment:
      ...
      - EdgeDeviceOptions__AgentID=d7996ca3-5937-4720-afe3-d2cf8f5ac210
      - EdgeDeviceOptions__NodeUrl=https://my-environment.tributech-node.com
      - EnrollmentOptions__EnrollmentCertBase64=LS0tLS1C...ZDdqb29rcUV
      - EnrollmentOptions__EnrollmentKeyBase64=AKS0tLS1C...ZDdqb29rcDE