tributech-agent:
    ...
    environment:
      ...
      - EdgeDeviceOptions__AgentID=729cbccb-116c-4eed-b25e-128590a436e2
      - EdgeDeviceOptions__NodeUrl=https://my-environment.tributech-node.com