version: "3.5"

services:
  source-mqtt:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}tributech-source-mqtt:${SOURCE_TAG:-latest}         
    depends_on:
      - mosquitto-server-mqtt
      - tributech-agent-mqtt
    environment:
      - MqttOptions__MQTTHost=mosquitto-server-mqtt
      - Logging__LogLevel__Default=Debug
    networks:
      - mqtt-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  tributech-agent-mqtt:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}tributech-agent:${AGENT_TAG:-latest}
    depends_on:
      - mosquitto-server-mqtt
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__Console__FormatterName=simple
      - MqttOptions__MQTTHost=mosquitto-server-mqtt
      # general DSK edge agent configuration  
      - EdgeDeviceOptions__AgentID=${AGENT_ID:?"The variable AGENT_ID needs to be configured in the .env file."}
    networks:
      - mqtt-net      
    ports:
      - "5000:80" # enable access to agent mqtt-API (e.g. for configuration with Agent-Companion)
    volumes:
      - ./volumes/mqtt/agent/:/app/data # volume mapping for permanent storage of keys and datatwin file
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"        

  mosquitto-server-mqtt:
    image: eclipse-mosquitto:${MQTT_TAG:-latest}
    networks:
      - mqtt-net
    ports: 
     - '1883:1883' # MQTT
    # - "127.0.0.1:9001:9001" # web-socket
    restart: unless-stopped


networks:
  mqtt-net: