version: "3.6"

services:
  official-opcua-server:
    image: ghcr.io/opcfoundation/uanetstandard/refserver:1.4.371.91
    hostname: off_opcua_server
    networks:
      - opcua-net
    volumes:
      - ./volumes/opcua/mock-server:/root/.local/share/OPC Foundation
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

volumes:
   official_opcua:
