version: "3.6"

services:
 mock-server-ads:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}tributech-source-ads-mock:${SOURCE_TAG:-latest}
    restart: unless-stopped
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:5000
     - AdsSettings__ServerName=MockADS
     - AdsSettings__ServerPort=851
     - AdsSettings__NeedsRouter=true
     - ServerStructureSettings__InitValues__0__Value=2200215101
     - ServerStructureSettings__InitValues__0__Path=Settings.stConfigFile.sSerialNumber
     - AmsRouter__Name=MockServerRouter
     - AmsRouter__NetId=172.24.1.6.1.1
     - AmsRouter__RemoteConnections__0__Name=TestClient
     - AmsRouter__RemoteConnections__0__NetId=172.24.1.5.1.1
     - AmsRouter__RemoteConnections__0__Address=172.24.1.5
     - ValueGeneratorSettings__Enabled=true
     - ValueGeneratorSettings__ChangeAllValuesEveryInterval=true
    #ports:
      # - "127.0.0.1:5000:5000" # SwaggerUI
      # - "127.0.0.1:48898:48898" # TCP Router Port
      # - "127.0.0.1:48899:49999/udp" # UDP Router Port
    networks:
      ads-net:
         ipv4_address: 172.24.1.6
