{
 "title": "Dataset: Simulated IoT Device data",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "IoT Device Machine 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Machine Temperature - °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  get_bytea_to_double(\"Values\", 0) as \"°C\"\nFROM \"Value\"\nWHERE\n  $__timeFilter(\"Timestamp\") and\n  \"ValueMetadataId\" = '<ReplaceWith: Machine Temperature ValueMetadataId>'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Air Temperature - °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  get_bytea_to_double(\"Values\", 0) as \"°C\"\nFROM \"Value\"\nWHERE\n  $__timeFilter(\"Timestamp\") and\n  \"ValueMetadataId\" = '<ReplaceWith: Air Temperature ValueMetadataId>'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Machine Pressure - Pa",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  get_bytea_to_double(\"Values\", 0) as \"°C\"\nFROM \"Value\"\nWHERE\n  $__timeFilter(\"Timestamp\") and\n  \"ValueMetadataId\" = '<ReplaceWith: Machine Pressure ValueMetadataId>'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Air Humidity - %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  get_bytea_to_double(\"Values\", 0) as \"%\"\nFROM \"Value\"\nWHERE\n  $__timeFilter(\"Timestamp\") and\n  \"ValueMetadataId\" = '<ReplaceWith: Air Humidity ValueMetadataId>'\nORDER BY 1\n"
    }
   ]
  }
 ]
}