version: "3.3"

services:
  # DSK agent
  dsk-agent:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}dsk-agent:${TAG:-latest}
    depends_on:
      - mosquitto-server     
    environment:
      - Logging__LogLevel__Default=Information
      - MqttOptions__MQTTHost=mosquitto-server
      # general DSK edge agent configuration  
      - EdgeDeviceOptions__AgentID=${AGENT_ID:?"The variable AGENT_ID needs to be configured in the .env file."}
      - EdgeDeviceOptions__ValueSink=HttpValueSink
      # configure DSK Data-API for value storage
      - DataApiValueSinkOptions__DataAPIBaseUrl=https://data-api.${NODE_NAME:?"The variable NODE_NAME needs to be configured in the .env file."}.dataspace-node.com/
      - DataApiValueSinkOptions__AuthUrl=https://auth.${HUB_NAME:?"The variable HUB_NAME needs to be configured in the .env file."}.dataspace-hub.com/auth/realms/${NODE_NAME:?"The variable NODE_NAME needs to be configured in the .env file."}/protocol/openid-connect/token
      - DataApiValueSinkOptions__ClientSecret=${DATA_API_SECRET:?"The variable DATA_API_SECRET needs to be configured in the .env file."}
      # configure DSK Trust-API for proof storage
      - ProofSinkOptions__TrustAPIBaseUrl=https://trust-api.${NODE_NAME:?"The variable NODE_NAME needs to be configured in the .env file."}.dataspace-node.com/
      - ProofSinkOptions__AuthUrl=https://auth.${HUB_NAME:?"The variable HUB_NAME needs to be configured in the .env file."}.dataspace-hub.com/auth/realms/${NODE_NAME:?"The variable NODE_NAME needs to be configured in the .env file."}/protocol/openid-connect/token
      - ProofSinkOptions__ClientSecret=${TRUST_API_SECRET:?"The variable TRUST_API_SECRET needs to be configured in the .env file."}
    networks:
      - edge-net      
    ports:
      - "5000:80" # enable access to agent REST-API (e.g. for configuration with Agent-Companion)
    volumes:
      - ./volumes/dsk-agent/:/app/data # volume mapping for permanent storage of keys and datatwin file
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"        

  # MQTT broker/server
  mosquitto-server:
    image: eclipse-mosquitto:1.6
    networks:
      - edge-net
    # Expose ports for development and testing purposes
    #ports:
    # - "127.0.0.1:1883:1883" # MQTT
    # - "127.0.0.1:9001:9001" # web-socket
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

networks:
  edge-net:

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
