version: "3.6"

services:
  source-rest:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}tributech-source-rest:${SOURCE_TAG:-latest}
    depends_on:
      - mosquitto-server-rest
      - tributech-agent-rest
    environment:
      - MqttOptions__MQTTHost=mosquitto-server-rest
      - Logging__LogLevel__Default=Debug
    ports:
      - "5080:8080"
    networks:
      - rest-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  tributech-agent-rest:
    image: ${DOCKER_REGISTRY-tributech.azurecr.io/}tributech-agent:${AGENT_TAG:-latest}
    depends_on:
      - mosquitto-server-rest
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__Console__FormatterName=simple
      - MqttOptions__MQTTHost=mosquitto-server-rest
      # general DSK edge agent configuration
      - EdgeDeviceOptions__AgentID=${AGENT_ID:?"The variable AGENT_ID needs to be configured in the .env file."}
    networks:
      - rest-net
    ports:
      - "5000:8080" # enable access to agent REST-API (e.g. for configuration with Agent-Companion)
    volumes:
      - ./volumes/rest/agent/:/app/data # volume mapping for permanent storage of keys and datatwin file
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"

  mosquitto-server-rest:
    image: eclipse-mosquitto:${MQTT_TAG:-1.6}
    networks:
      - rest-net
    # ports:
    # - '1883:1883' # MQTT
    # - "127.0.0.1:9001:9001" # web-socket
    restart: unless-stopped


networks:
  rest-net:
