name: Tributech CI - main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/*, hotfix/*, fix/* ]



jobs:

    publish:
        name: docs via GitHub Pages
        uses: tributech-solutions/tributech-github-actions-ci/.github/workflows/deploy-gh-pages.yaml@deploy-gh-page-blob-storage-testing
        with:
          DOTNET_VERSION: '16.x'
        secrets:
          GH_PAGES_DEPLOY: ${{ secrets.GH_PAGES_DEPLOY }}